-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES TABLE
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  email text,
  bio text,
  location text,
  avatar_url text,
  dashboard_layout jsonb,
  widgets_order jsonb,
  enabled_widgets jsonb,
  theme text,
  notifications_preferences jsonb
);

alter table public.profiles enable row level security;

create policy "Users can view their own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update their own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert their own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- 2. TASKS TABLE
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  subtitle text,
  urgent boolean default false,
  tag text,
  tag_color text,
  completed boolean default false,
  created_at timestamp with time zone default now(),
  status text default 'todo'
);

alter table public.tasks enable row level security;

create policy "Users can view their own tasks" on public.tasks
  for select using (auth.uid() = user_id);

create policy "Users can insert their own tasks" on public.tasks
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own tasks" on public.tasks
  for update using (auth.uid() = user_id);

create policy "Users can delete their own tasks" on public.tasks
  for delete using (auth.uid() = user_id);

-- 3. TRANSACTIONS TABLE
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  type text check (type in ('income', 'expense')),
  amount numeric not null,
  category text,
  title text,
  date date,
  created_at timestamp with time zone default now()
);

alter table public.transactions enable row level security;

create policy "Users can view their own transactions" on public.transactions
  for select using (auth.uid() = user_id);

create policy "Users can insert their own transactions" on public.transactions
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own transactions" on public.transactions
  for update using (auth.uid() = user_id);

create policy "Users can delete their own transactions" on public.transactions
  for delete using (auth.uid() = user_id);

-- 4. CALENDAR EVENTS TABLE
create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  color text,
  event_date date,
  location text,
  created_at timestamp with time zone default now()
);

-- Add location column if it doesn't exist (idempotent check)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'calendar_events' and column_name = 'location') then
    alter table public.calendar_events add column location text;
  end if;
end $$;

alter table public.calendar_events enable row level security;

create policy "Users can view their own events" on public.calendar_events
  for select using (auth.uid() = user_id);

create policy "Users can insert their own events" on public.calendar_events
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own events" on public.calendar_events
  for update using (auth.uid() = user_id);

create policy "Users can delete their own events" on public.calendar_events
  for delete using (auth.uid() = user_id);

-- 5. POMODOROS TABLE
create table if not exists public.pomodoros (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  duration integer not null,
  completed boolean default false,
  created_at timestamp with time zone default now()
);

alter table public.pomodoros enable row level security;

create policy "Users can view their own pomodoros" on public.pomodoros
  for select using (auth.uid() = user_id);

create policy "Users can insert their own pomodoros" on public.pomodoros
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own pomodoros" on public.pomodoros
  for update using (auth.uid() = user_id);

create policy "Users can delete their own pomodoros" on public.pomodoros
  for delete using (auth.uid() = user_id);

-- 6. HANDLE NEW USER TRIGGER
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url, email)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Recreate trigger to ensure it's up to date
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
